'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm2

    '''<summary>
    '''UserNameHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserNameHF As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''LessonIDHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LessonIDHF As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''DateCreatedlbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateCreatedlbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Progresslbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Progresslbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Feedbacklbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Feedbacklbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ChooseLessonlbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChooseLessonlbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''LessonNameDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LessonNameDDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''CompletedLessons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompletedLessons As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''QuizHistory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuizHistory As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''QuizHistoryPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuizHistoryPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''QuizHistoryRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuizHistoryRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''QuizHistoryChart control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuizHistoryChart As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''QuizAttemptlbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuizAttemptlbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''QuizAttemptDLL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuizAttemptDLL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''QuizAttemptOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuizAttemptOrder As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''AttemptOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AttemptOrder As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''QuizAttemptPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuizAttemptPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''QuizAttemptRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuizAttemptRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CompletedGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CompletedGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''LessonsCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LessonsCompleted As Global.System.Web.UI.WebControls.AccessDataSource

    '''<summary>
    '''panelContainer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents panelContainer As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''NotCompletedGridView control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NotCompletedGridView As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''NotCompleted control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NotCompleted As Global.System.Web.UI.WebControls.AccessDataSource
End Class
