'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm4

    '''<summary>
    '''IndexHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IndexHF As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TaskNumberHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TaskNumberHF As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''HFLessonID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HFLessonID As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''NumTaskAttemptsHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NumTaskAttemptsHF As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''LessonName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LessonName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SQLLessonPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SQLLessonPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ExplanationLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExplanationLink As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''SyntaxLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SyntaxLink As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ExampleLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExampleLink As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''VideoLink control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VideoLink As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''ExplanationPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExplanationPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DisplayExplanationlbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DisplayExplanationlbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SyntaxPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SyntaxPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DisplaySyntaxlbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DisplaySyntaxlbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ExamplePanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExamplePanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''DisplayExamplelbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DisplayExamplelbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''IntroductionPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IntroductionPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Introductionlbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Introductionlbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''VideoPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents VideoPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''Videolbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Videolbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NextPagebtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NextPagebtn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ActivityPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActivityPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ActivityTitlelbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActivityTitlelbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Progresslbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Progresslbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ActivityNumberlbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActivityNumberlbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ActivityInstructionlbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ActivityInstructionlbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UserInputtxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserInputtxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Submitbtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submitbtn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''NextQuestbtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NextQuestbtn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''InfoPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InfoPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CorrectPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CorrectPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CorrectFeedbacklbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CorrectFeedbacklbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''WrongPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WrongPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''WrongFeedbacklbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WrongFeedbacklbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ShowAnstxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowAnstxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ShowAnsbtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ShowAnsbtn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''TakeQuizbtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TakeQuizbtn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ResultPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResultPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''GridView1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GridView1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ExercisesDB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExercisesDB As Global.System.Web.UI.WebControls.AccessDataSource
End Class
