'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class WebForm5

    '''<summary>
    '''LessonIDHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LessonIDHF As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''IndexHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IndexHF As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''NumCorrectHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NumCorrectHF As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''QuestionNumberHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuestionNumberHF As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''MaxIndexHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MaxIndexHF As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''QuizIDHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuizIDHF As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''TotalQuestionsHF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TotalQuestionsHF As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''QuizIntroPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuizIntroPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ConfirmButton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ConfirmButton As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''QuizPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuizPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''QuizTitlelbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuizTitlelbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''QuizImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuizImage As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''TableNamelbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TableNamelbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''QuestionNumberlbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuestionNumberlbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''QuizQuestionlbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuizQuestionlbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Progresslbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Progresslbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UserInputtxt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UserInputtxt As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Submitbtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Submitbtn As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''QuizSummaryPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuizSummaryPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''SummaryTitlelbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SummaryTitlelbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''QuizReportRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents QuizReportRepeater As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''Feedbacklbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Feedbacklbl As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NextLessonbtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NextLessonbtn As Global.System.Web.UI.WebControls.Button
End Class
